/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderRequest {
  customerId?: string | null;
  customerName?: string | null;
  orderNo?: string | null;
  status?: string | null;
  total?: number;
}
