/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiV1IdentityUsersPost$Params as ApiV1IdentityUsersPost$Params } from './fn/app-host/api-v-1-identity-users-post';
export { apiV1IdentityUsersPost as apiV1IdentityUsersPost } from './fn/app-host/api-v-1-identity-users-post';
export type { ApiV1IdentityUsersIdGet$Params as ApiV1IdentityUsersIdGet$Params } from './fn/app-host/api-v-1-identity-users-id-get';
export { apiV1IdentityUsersIdGet as apiV1IdentityUsersIdGet } from './fn/app-host/api-v-1-identity-users-id-get';
export type { ApiV1SalesOrdersPost$Params as ApiV1SalesOrdersPost$Params } from './fn/app-host/api-v-1-sales-orders-post';
export { apiV1SalesOrdersPost as apiV1SalesOrdersPost } from './fn/app-host/api-v-1-sales-orders-post';
export type { ApiV1SalesOrdersIdGet$Params as ApiV1SalesOrdersIdGet$Params } from './fn/app-host/api-v-1-sales-orders-id-get';
export { apiV1SalesOrdersIdGet as apiV1SalesOrdersIdGet } from './fn/app-host/api-v-1-sales-orders-id-get';
export type { ApiV1InventoryProductsPost$Params as ApiV1InventoryProductsPost$Params } from './fn/app-host/api-v-1-inventory-products-post';
export { apiV1InventoryProductsPost as apiV1InventoryProductsPost } from './fn/app-host/api-v-1-inventory-products-post';
export type { ApiV1InventoryProductsIdGet$Params as ApiV1InventoryProductsIdGet$Params } from './fn/app-host/api-v-1-inventory-products-id-get';
export { apiV1InventoryProductsIdGet as apiV1InventoryProductsIdGet } from './fn/app-host/api-v-1-inventory-products-id-get';
